### ISSUE TITLE
how install database?

### ISSUE THREAD

**Issue by ghanbari** [KyleU/solitaire.gg#1]
hi, thanks for sharing code
how can i configure database and create schema?, i don't know where parameters is defined
when i run and open site, i get this error:
```
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Line -> 307, File -> auth.c, SQLSTATE -> 28P01, Routine -> auth_failed, Message -> password authentication failed for user "solitaire", Severity -> FATAL))
  at utils.ApplicationContext.<init>(ApplicationContext.scala:27)
  at utils.ApplicationContext.class(ApplicationContext.scala:26)
  while locating utils.ApplicationContext
    for parameter 0 at controllers.HomeController.<init>(HomeController.scala:9)
```

thank you

**Comment by KyleU** [comment]
Yeah, I need better setup instructions. Check `conf/application.conf`'s database section. You'll need valid postgres credentials.

**Comment by ghanbari** [comment]
thank you for help & nice project
