### ISSUE TITLE
[Wishlist] Extract a standalone command line solver

### ISSUE THREAD

**Issue by shlomif** [KyleU/solitaire.gg#70]
Hi!

Would it be possible to extract command line solvers based on the scala API? I got reminded of it due to this - http://fc-solve.shlomifish.org/faq.html#deal_11982 . Thanks!

**Comment by KyleU** [comment]
I’d love to, but it would only work with my game format, so it’d be pretty useless unless the game used a known seed algorithm, like PysolFC does with Microsoft’s Freecell implementation.

**Comment by shlomif** [comment]
On Sun, 20 May 2018 14:02:44 -0700
Kyle Unverferth <notifications@github.com> wrote:

> I’d love to, but it would only work with my game format, so it’d be pretty
> useless unless the game used a known seed algorithm, like PysolFC does with
> Microsoft’s Freecell implementation. 
> 

Would not it be possible to read the initial position from a YAML / JSON / XML
or other serial format?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Best Introductory Programming Language - http://shlom.in/intro-lang

I wear prescription glasses so I may be half-blind, but at least I'm trying
hard not to be a complete dick.
    — https://twitter.com/shlomif/status/480765130242662400

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by KyleU** [comment]
Yeah, that'd be easy enough. Are there any existing formats worth stealing? I doubt a custom format would ever get traction. Also, full disclosure, the solver is dumb as hell, basically just does a depth-first search of game moves using the same API as a normal game, passing moves and undos, waiting for a win event. But I guess a command-line version would be a good first step before improving the solver.

**Comment by shlomif** [comment]
Hi,

On Tue, 22 May 2018 16:10:23 +0000 (UTC)
Kyle Unverferth <notifications@github.com> wrote:

> Yeah, that'd be easy enough. Are there any existing formats worth stealing? I
> doubt a custom format would ever get traction. Also, full disclosure, the
> solver is dumb as hell, basically just does a depth-first search of game
> moves using the same API as a normal game, passing moves and undos, waiting
> for a win event. But I guess a command-line version would be a good first
> step before improving the solver.
> 

there is the format that fc-solve accepts and emits -
http://fc-solve.shlomifish.org/verify-code/ . Other solvers accept different
formats and I've written some converters and wrappers.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Google-Discontinues-Services/

I achieved my fast times by multitudes of 1% reductions.
— Bill Raymond in
https://groups.yahoo.com/neo/groups/fc-solve-discuss/conversations/messages/222

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@KyleU : hi! I gave a shot at trying to resolve this issue, but sbt gives me this on mageia linux 7:

```
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.7: configuration not public in org.scala-lang#scala-library;2.10.7: 'test'. It was required from org.scala-tools.sbinary#sbinary_2.10;0.4.2 default
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

```

I'm not blaming you, but java/JVM/etc. are known for being painful - at least on mageia. Perhaps I should use a debian unstable or ubuntu VM or container…

**Comment by shlomif** [comment]
I should note that the list of the converters is here for now - https://github.com/shlomif/fc-solve/blob/master/fc-solve/docs/solution-and-layout-formats-converters-and-wrappers.md ,

**Comment by shlomif** [comment]
@KyleU : hi! Seems like sbt cannot be installed on debian unstable using apt due to this - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873341 .
